sudo:
  - required

services:
  - docker
#  - conda

language:
  - python

python:
  - 3.6

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
  - pip install --progress-bar off -r requirements.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION dep1 dep2 ...
  - conda activate test-environment
  - python setup.py install

before_script:
  - ls
  - conda create -n env-python2.7-mxnet1.0.0 python=2.7

script:
  - pytest -q test_class.py
