sudo:
  - required

services:
  - docker

language:
  - python

python:
  - 3.6

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
  - pip install --progress-bar off -r requirements.txt

script:
  - pytest -q test_class.py
